# hosts/tf2/hardware-configuration.nix
#
# Minimal hardware stub for CI evaluation.
# Replace with the real hardware-configuration.nix after provisioning
# the NixOS VM (generated by `nixos-generate-config`).
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.loader.grub = {
    enable = true;
    device = "/dev/sda"; # placeholder — real value from nixos-generate-config
  };

  fileSystems."/" = {
    device = "/dev/sda1"; # placeholder
    fsType = "ext4";
  };
}
