# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  auto-steam-update = {
    pname = "auto-steam-update";
    version = "5a8378eb938cbb29d4dd45404a3f4d067c2c58c7";
    src = fetchgit {
      url = "https://github.com/Sarabveer/SM-Plugins.git";
      rev = "5a8378eb938cbb29d4dd45404a3f4d067c2c58c7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-tCbdpDd+8MExv/vobPcvfwx6GzUkndBMOmx2a8ZIgE0=";
    };
    date = "2018-06-27";
  };
  demostf = {
    pname = "demostf";
    version = "d8d313b53883d6bc33d959c7f4e6eb75c3f4dc5d";
    src = fetchgit {
      url = "https://github.com/demostf/plugin.git";
      rev = "d8d313b53883d6bc33d959c7f4e6eb75c3f4dc5d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JbxeuKC3jKMmBhNXsJZJxLAy3/984Zweo20gNND3XW0=";
    };
    date = "2025-05-21";
  };
  mapdownloader = {
    pname = "mapdownloader";
    version = "729db2ea9e7f353ca67d2c7c19e1cd1dc473928c";
    src = fetchgit {
      url = "https://github.com/spiretf/mapdownloader.git";
      rev = "729db2ea9e7f353ca67d2c7c19e1cd1dc473928c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-vc6wfjGZf2qoyRzfWgLzuP1q/pnRoS/VPsntva89E6s=";
    };
    date = "2025-06-15";
  };
  neocurl = {
    pname = "neocurl";
    version = "v2.0.1-beta1";
    src = fetchFromGitHub {
      owner = "sapphonie";
      repo = "SM-neocurl-ext";
      rev = "v2.0.1-beta1";
      fetchSubmodules = false;
      sha256 = "sha256-R4DnH8oJ1dsh/NfCNRHx8/yTSAo7liWrbQALk4u2esI=";
    };
  };
  p4sstime = {
    pname = "p4sstime";
    version = "v2.6.3";
    src = fetchFromGitHub {
      owner = "p4sstime";
      repo = "p4sstime-server-resources";
      rev = "v2.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-77BeUJMoLibnGG4uaQPdx+r4+95Q1S5Ho6nCDwMcW5U=";
    };
  };
  rgl-server-resources = {
    pname = "rgl-server-resources";
    version = "v372";
    src = fetchFromGitHub {
      owner = "RGLgg";
      repo = "server-resources-updater";
      rev = "v372";
      fetchSubmodules = false;
      sha256 = "sha256-ah5SaYjewGPlaUc3oybro6MG/fWSlJZyNA4OlLAgOD8=";
    };
  };
  soap = {
    pname = "soap";
    version = "v4.4.8";
    src = fetchFromGitHub {
      owner = "sapphonie";
      repo = "SOAP-TF2DM";
      rev = "v4.4.8";
      fetchSubmodules = false;
      sha256 = "sha256-/asvj8w+F3lGlH4sfsSvOS3ACrXOp8gCLmpagehfANg=";
    };
  };
}
